# Generated by Django 4.0.4 on 2022-04-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaner',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('phoneNumber', models.CharField(max_length=60)),
                ('isWorking', models.BooleanField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
