# Generated by Django 4.0.4 on 2022-04-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleanersinfo',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('surname', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('phonenumber', models.TextField(blank=True, db_column='phoneNumber', null=True)),
                ('isworking', models.BinaryField(blank=True, db_column='isWorking', null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cleanersInfo',
                'managed': False,
            },
        ),
    ]
