# Generated by Django 4.0.4 on 2022-04-19 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_cleanersinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cleaner',
        ),
    ]
